
version: "{build}"

image: Visual Studio 2013

branches:
  only:
  - master

configuration:
- RelWithDebInfo

build:
  parallel: true
  verbosity: minimal

build_script:
  - cmd: "tools/build.bat"
  - cmd: "tools/build_x64.bat"

artifacts:
- path: arma3urlfetch.dll
  name: arma3urlfetch_win32
- path: arma3urlfetch_x64.dll
  name: arma3urlfetch_win64
